package deputy.ttb.com.deputy.GreenDaoDB;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BUSINESS_INFO".
 */
@Entity
public class BusinessInfo {

    @Id
    private Long id;

    @NotNull
    @Unique
    private String name;

    @NotNull
    private String logoUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public BusinessInfo() {
    }

    public BusinessInfo(Long id) {
        this.id = id;
    }

    @Generated
    public BusinessInfo(Long id, String name, String logoUrl) {
        this.id = id;
        this.name = name;
        this.logoUrl = logoUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getLogoUrl() {
        return logoUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogoUrl(@NotNull String logoUrl) {
        this.logoUrl = logoUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
