package deputy.ttb.com.deputy.GreenDaoDB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import deputy.ttb.com.deputy.GreenDaoDB.BusinessInfo;

import deputy.ttb.com.deputy.GreenDaoDB.BusinessInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig businessInfoDaoConfig;

    private final BusinessInfoDao businessInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        businessInfoDaoConfig = daoConfigMap.get(BusinessInfoDao.class).clone();
        businessInfoDaoConfig.initIdentityScope(type);

        businessInfoDao = new BusinessInfoDao(businessInfoDaoConfig, this);

        registerDao(BusinessInfo.class, businessInfoDao);
    }
    
    public void clear() {
        businessInfoDaoConfig.clearIdentityScope();
    }

    public BusinessInfoDao getBusinessInfoDao() {
        return businessInfoDao;
    }

}
