package deputy.ttb.com.deputy.GreenDaoDB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import deputy.ttb.com.deputy.GreenDaoDB.ShiftDetails;

import deputy.ttb.com.deputy.GreenDaoDB.ShiftDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shiftDetailsDaoConfig;

    private final ShiftDetailsDao shiftDetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shiftDetailsDaoConfig = daoConfigMap.get(ShiftDetailsDao.class).clone();
        shiftDetailsDaoConfig.initIdentityScope(type);

        shiftDetailsDao = new ShiftDetailsDao(shiftDetailsDaoConfig, this);

        registerDao(ShiftDetails.class, shiftDetailsDao);
    }
    
    public void clear() {
        shiftDetailsDaoConfig.clearIdentityScope();
    }

    public ShiftDetailsDao getShiftDetailsDao() {
        return shiftDetailsDao;
    }

}
