package deputy.ttb.com.deputy.GreenDaoDB;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SHIFT_DETAILS".
 */
@Entity
public class ShiftDetails {

    @Id
    private Long id;

    @NotNull
    @Unique
    private String shiftDetails;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ShiftDetails() {
    }

    public ShiftDetails(Long id) {
        this.id = id;
    }

    @Generated
    public ShiftDetails(Long id, String shiftDetails) {
        this.id = id;
        this.shiftDetails = shiftDetails;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getShiftDetails() {
        return shiftDetails;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShiftDetails(@NotNull String shiftDetails) {
        this.shiftDetails = shiftDetails;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
